dirs = ["~/Coding/", "~/Developer/"]

[profile.unstoppable]
CLOUDFLARE_API_KEY = "UNSTOPPABLE_CLOUDFLARE_API_KEY"
CLOUDFLARE_EMAIL = "UNSTOPPABLE_CLOUDFLARE_EMAIL"
CLOUDFLARE_DEFAULT_ACCOUNT_ID = "UNSTOPPABLE_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN = "UNSTOPPABLE_CLOUDFLARE_API_TOKEN"
AWS_ACCESS_KEY_ID = "UNSTOPPABLE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "UNSTOPPABLE_AWS_SECRET_ACCESS_KEY"
TURSO_API_TOKEN = "UNSTOPPABLE_TURSO_TOKEN"

[profile.attendance]
AWS_ACCESS_KEY_ID = "ATTENDANCE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "ATTENDANCE_AWS_SECRET_ACCESS_KEY"

[profile.lockinai]
AWS_ACCESS_KEY_ID = "LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY = "LOCKINAI_AWS_SECRET_KEY"
CLOUDFLARE_DEFAULT_ACCOUNT_ID = "LOCKINAI_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN = "LOCKINAI_CLOUDFLARE_API_TOKEN"

[profile.brainrot]
TURSO_API_TOKEN = "RGODHA_TURSO_API_TOKEN"
AWS_ACCESS_KEY_ID = "LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY = "LOCKINAI_AWS_SECRET_KEY"
CLOUDFLARE_API_TOKEN = "GRIFFIN_SCHOOL_CLOUDFLARE_API_TOKEN"
CLOUDFLARE_DEFAULT_ACCOUNT_ID = "GRIFFIN_SCHOOL_CLOUDFLARE_ACCOUNT_ID"
STRIPE_LIVE_KEY = "GRIFFIN_SCHOOL_STRIPE_LIVE_SECRET"
STRIPE_TEST_KEY = "GRIFFIN_SCHOOL_STRIPE_TEST_SECRET"

[project]
unstoppable = ["unstoppable"]
attendance = ["attendance"]
"brainrot.mov" = ["brainrot"]

[project.old-asset]
profiles = ["unstoppable"]
vars = { SUPABASE_TOKEN = "UNSTOPPABLE_SUPABASE_TOKEN", SUPABASE_ORG_ID = "UNSTOPPABLE_SUPABASE_ORG_ID" }
