dirs = ["~/Coding/", "~/Developer/"]

[profile.unstoppable]
CLOUDFLARE_API_KEY = "UNSTOPPABLE_CLOUDFLARE_API_KEY"
CLOUDFLARE_EMAIL = "UNSTOPPABLE_CLOUDFLARE_EMAIL"
CLOUDFLARE_DEFAULT_ACCOUNT_ID = "UNSTOPPABLE_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN = "UNSTOPPABLE_CLOUDFLARE_API_TOKEN"
AWS_ACCESS_KEY_ID = "UNSTOPPABLE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "UNSTOPPABLE_AWS_SECRET_ACCESS_KEY"
TURSO_API_TOKEN = "UNSTOPPABLE_TURSO_TOKEN"

[profile.attendance]
AWS_ACCESS_KEY_ID = "ATTENDANCE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "ATTENDANCE_AWS_SECRET_ACCESS_KEY"

[profile.lockinai]
AWS_ACCESS_KEY_ID = "LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY = "LOCKINAI_AWS_SECRET_KEY"
CLOUDFLARE_DEFAULT_ACCOUNT_ID = "LOCKINAI_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN = "LOCKINAI_CLOUDFLARE_API_TOKEN"

[profile.brainrot]
AWS_ACCESS_KEY_ID = "LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY = "LOCKINAI_AWS_SECRET_KEY"
CLOUDFLARE_API_TOKEN = "GRIFFIN_SCHOOL_CLOUDFLARE_API_TOKEN"
CLOUDFLARE_DEFAULT_ACCOUNT_ID = "GRIFFIN_SCHOOL_CLOUDFLARE_ACCOUNT_ID"
STRIPE_LIVE_KEY = "GRIFFIN_SCHOOL_STRIPE_LIVE_SECRET"
STRIPE_TEST_KEY = "GRIFFIN_SCHOOL_STRIPE_TEST_SECRET"

[profile.ai]
# XAI_API_KEY = "XAI_API_KEY"
# DEEPSEEK_API_KEY = "DEEPSEEK_API_KEY"
# OPENROUTER_API_KEY = "OPENROUTER_API_KEY"
GOOGLE_GENERATIVE_AI_API_KEY = "GEMINI_API_KEY"
ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"
# AWS_REGION = "AWS_REGION"
# AWS_ACCESS_KEY_ID = "AI_AWS_ACCESS_KEY_ID"
# AWS_SECRET_ACCESS_KEY = "AI_AWS_SECRET_ACCESS_KEY"
DEEPGRAM_API_KEY = "DEEPGRAM_API_KEY"

[project]
unstoppable = ["unstoppable"]
attendance = ["attendance"]
"brainrot.mov" = ["brainrot"]
sst = ["brainrot"]

[project.old-asset]
profiles = ["unstoppable"]
vars = { SUPABASE_TOKEN = "UNSTOPPABLE_SUPABASE_TOKEN", SUPABASE_ORG_ID = "UNSTOPPABLE_SUPABASE_ORG_ID" }

[project.agentic-brainrot.vars]
CLOUDFLARE_API_TOKEN = "BROWSER_RENDERING_CF_API_TOKEN"
CLOUDFLARE_DEFAULT_ACCOUNT_ID = "GRIFFIN_SCHOOL_CLOUDFLARE_ACCOUNT_ID"
BRAINROT_API_KEY = "BRAINROT_API_KEY"
