dirs = ["~/Coding/"]

[projects.unstoppable-asset.vars]
CLOUDFLARE_API_KEY="UNSTOPPABLE_CLOUDFLARE_API_KEY"
CLOUDFLARE_EMAIL="UNSTOPPABLE_CLOUDFLARE_EMAIL"
CLOUDFLARE_DEFAULT_ACCOUNT_ID="UNSTOPPABLE_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN="UNSTOPPABLE_CLOUDFLARE_API_TOKEN"
SUPABASE_TOKEN="UNSTOPPABLE_SUPABASE_TOKEN"
SUPABASE_ORG_ID="UNSTOPPABLE_SUPABASE_ORG_ID"
