dirs = ["~/Coding/", "~/Developer/"]

[projects.old-asset.vars]
CLOUDFLARE_API_KEY="UNSTOPPABLE_CLOUDFLARE_API_KEY"
CLOUDFLARE_EMAIL="UNSTOPPABLE_CLOUDFLARE_EMAIL"
CLOUDFLARE_DEFAULT_ACCOUNT_ID="UNSTOPPABLE_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN="UNSTOPPABLE_CLOUDFLARE_API_TOKEN"
SUPABASE_TOKEN="UNSTOPPABLE_SUPABASE_TOKEN"
SUPABASE_ORG_ID="UNSTOPPABLE_SUPABASE_ORG_ID"
AWS_ACCESS_KEY_ID="UNSTOPPABLE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY="UNSTOPPABLE_AWS_SECRET_ACCESS_KEY"

[projects.unstoppable.vars]
CLOUDFLARE_DEFAULT_ACCOUNT_ID="UNSTOPPABLE_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN="UNSTOPPABLE_CLOUDFLARE_API_TOKEN"
TURSO_API_TOKEN="UNSTOPPABLE_TURSO_TOKEN"
AWS_ACCESS_KEY_ID="UNSTOPPABLE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY="UNSTOPPABLE_AWS_SECRET_ACCESS_KEY"

[projects.attendance.vars]
AWS_ACCESS_KEY_ID="ATTENDANCE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY="ATTENDANCE_AWS_SECRET_ACCESS_KEY"

[projects.QuizAI.vars]
AWS_ACCESS_KEY_ID="QUIZ_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY="QUIZ_AWS_SECRET_KEY"

[projects.LockInAI.vars]
TURSO_API_TOKEN="RGODHA_TURSO_API_TOKEN"
AWS_ACCESS_KEY_ID="LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY="LOCKINAI_AWS_SECRET_KEY"
CLOUDFLARE_DEFAULT_ACCOUNT_ID="LOCKINAI_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN="LOCKINAI_CLOUDFLARE_API_TOKEN"

[projects.ecoflare.vars]
TURSO_API_TOKEN="RGODHA_TURSO_API_TOKEN"
AWS_ACCESS_KEY_ID="LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY="LOCKINAI_AWS_SECRET_KEY"

[projects.dexcom-downloader.vars]
TURSO_API_TOKEN="RGODHA_TURSO_API_TOKEN"
AWS_ACCESS_KEY_ID="LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY="LOCKINAI_AWS_SECRET_KEY"

[projects.sst.vars]
AWS_ACCESS_KEY_ID="LOCKINAI_AWS_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY="LOCKINAI_AWS_SECRET_KEY"
