dirs = ["~/Coding/"]

[projects.unstoppable-asset.vars]
CLOUDFLARE_API_KEY="UNSTOPPABLE_CLOUDFLARE_API_KEY"
CLOUDFLARE_EMAIL="UNSTOPPABLE_CLOUDFLARE_EMAIL"
CLOUDFLARE_DEFAULT_ACCOUNT_ID="UNSTOPPABLE_CLOUDFLARE_DEFAULT_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN="UNSTOPPABLE_CLOUDFLARE_API_TOKEN"
SUPABASE_TOKEN="UNSTOPPABLE_SUPABASE_TOKEN"
SUPABASE_ORG_ID="UNSTOPPABLE_SUPABASE_ORG_ID"
AWS_ACCESS_KEY_ID="UNSTOPPABLE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY="UNSTOPPABLE_AWS_SECRET_ACCESS_KEY"

[projects.attendance.vars]
AWS_ACCESS_KEY_ID="ATTENDANCE_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY="ATTENDANCE_AWS_SECRET_ACCESS_KEY"
